spring:
  main:
    banner-mode: "OFF"
  output:
    ansi:
      enabled: DETECT

logging:
  level:
    root: INFO
    backdev.infrastructure.configuration: DEBUG
    backdev.domain.product: DEBUG
  file:
    name: "log/backdev-test.log"
  logback:
    rollingpolicy:
      total-size-cap: 4 GB
      max-file-size: 100 MB
      max-history: 7

resilience4j.circuitbreaker:
    instances:
      similarIds:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      product:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

service:
  similar-products:
    parallelism: 5

repository:
  product:
    cache:
      duration: 30_000

server:
  port: 5000

endpoint:
  status:
    path: "/status"
  product:
    path:
      base: "/product"
      by-id: "${endpoint.product.path.base}/{product_id}"
      similar: "${endpoint.product.path.by-id}/similar"

client:
  product:
    url: "http://localhost:3001"